name: Docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        env:
          CLIENT_ID: "test_client"
          CLIENT_SECRET: "test_client-secret"
          FRONTEND_URL: "http://127.0.0.1:3000"
          NEXT_PUBLIC_API_URL: "http://127.0.0.1:8080"
        run: docker compose build